## Build Codenames docker image from the latest sources from the git repo

FROM node:12 AS builder
WORKDIR /data
RUN git clone --depth=1 https://github.com/koldoon/codenames-game.git
WORKDIR /data/codenames-game
RUN npm install && npm run build

FROM mhart/alpine-node:slim-12
WORKDIR /svc/codenames
COPY --from=builder /data/codenames-game/dist ./
VOLUME /svc/codenames/data
ENTRYPOINT node ./server/main.js
EXPOSE 8095
